services:
  - type: web
    name: LC Made Quick  # ğŸ” Change this to your preferred site name
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    autoDeploy: true